version: "3"

networks:
  gateway:
    external: true
    name: gateway

services:
  nexus:
    container_name: nexus3
    image: sonatype/nexus3
    restart: unless-stopped
    ports:
      - "18081:8081"
    volumes:
      - "$INSTALL_DIR/data:/nexus-data"
    networks:
      - gateway
